Implement websockets and add a market maker bot
neilvyas/ucf_exchange_client pull request #1
Opened 2016-11-13 21:12 UTC by macalinao

2016-11-13 21:42 UTC, neilvyas commented on ucf_exchange_client/app.py
> +            for part in resp: self.conn.write(part)
newline pls

2016-11-13 21:42 UTC, neilvyas commented on ucf_exchange_client/app.py
> +import asyncio
alphabetize import pls

2016-11-13 21:43 UTC, neilvyas commented on ucf_exchange_client/connection.py
> +from .RPC_types import msg_from_json, msg_to_json
so I just changed this functionality on `master`, you should `import json` and `json.dumps` the message yourself.

2016-11-13 23:39 UTC, neilvyas requested changes
Pretty good. Need to actually flesh out the market maker bot. `async` code looks good but maybe needs tests? I don't have `asyncio` experience.

2016-11-13 23:39 UTC, neilvyas commented on examples/market_maker.py
> +market_maker.run('localhost', 8166)
does this actually work?

2016-11-13 23:39 UTC, neilvyas commented on examples/market_maker.py
> +market_maker = Strategy('mm')
So as-written this strategy doesn't actually issue any trades. You should define a method that handles `Book` or something and actually does like `yield Buy(ticker, price, quantity)`.

2016-11-13 23:39 UTC, neilvyas commented on examples/market_maker.py
> +from ucf_exchange_client import Strategy
you should also import `Buy`, `Sell`, `Cancel`.

2016-11-13 23:39 UTC, neilvyas commented on examples/market_maker.py
> +@market_maker.handle('Hello')
This is now called `'Handshake`.

2016-11-13 23:39 UTC, neilvyas commented on ucf_exchange_client/app.py
> +
one newline between method definitions pls

2016-11-13 23:39 UTC, neilvyas commented on ucf_exchange_client/connection.py
> +    """The connection to the UCF exchange backend."""
s/backend/server

2016-11-14 20:59 UTC, macalinao commented on examples/market_maker.py
> +market_maker.run('localhost', 8166)
In theory. I don't know since we don't have a server.

2016-11-14 21:00 UTC, macalinao commented on ucf_exchange_client/app.py
> +
there is. You had trailing whitespace here.

2016-11-14 21:00 UTC, macalinao commented on ucf_exchange_client/connection.py
> +    """The connection to the UCF exchange backend."""
Done.

2016-11-14 21:01 UTC, macalinao commented on examples/market_maker.py
> +market_maker = Strategy('mm')
ah, I thought this was complete. I'm just going to port my old market maker bot to this API.

2016-11-14 21:01 UTC, macalinao commented on examples/market_maker.py
> +from ucf_exchange_client import Strategy
Ack.

2016-11-14 21:01 UTC, macalinao commented on examples/market_maker.py
> +@market_maker.handle('Hello')
Done.

2016-11-14 21:03 UTC, macalinao commented
@neilvyas I don't think tests in the I/O code are worth it. We should just do an integration test.

2016-11-14 21:29 UTC, neilvyas commented on ucf_exchange_client/app.py
> +
right, thanks. `vim` should have picked that up...

2016-11-14 21:30 UTC, neilvyas commented on examples/market_maker.py
> +market_maker.run('localhost', 8166)
I think I meant this more as a rhetorical question. in any case, you should import-guard this:

```python
if __name__ == "__main__":
  market_maker.run('localhost', 8166)
```

2016-11-14 21:35 UTC, macalinao commented on examples/market_maker.py
> +market_maker.run('localhost', 8166)
good point my friend

2016-11-14 21:35 UTC, macalinao commented on ucf_exchange_client/app.py
> +
`M-x delete-trailing-whitespace`

2016-11-14 21:35 UTC, neilvyas commented
yeah, I will merge without coverage and we can add coverage later. I'd like to get the changes to `Strategy` in before we get hella merge conflicts.

2016-11-14 21:36 UTC, neilvyas requested changes
i think this is broken

2016-11-14 21:36 UTC, neilvyas commented on ucf_exchange_client/app.py
> +            resp = await self._handle(msg)
I don't think you need to await this? It's not an async operation, and `_handle` isn't async-def'd anyway.

2016-11-14 21:37 UTC, macalinao commented on ucf_exchange_client/app.py
> +            resp = await self._handle(msg)
Done.

2016-11-14 21:39 UTC, neilvyas commented
ok, will merge as soon as mm bot is ported.

2016-11-15 01:40 UTC, merged